/**
 * Detect disposable / temporary email addresses.
 *
 * Client-side heuristic list of common throwaway providers. Not exhaustive
 * (new providers appear constantly) but catches the vast majority of casual
 * throwaway signups. For higher assurance, pair with a server-side lookup.
 */

// Common disposable / temp-mail domains. Sorted, deduped.
const DISPOSABLE_DOMAINS = new Set<string>([
  "0-mail.com", "0wnd.net", "0wnd.org", "10minutemail.com", "10minutemail.net",
  "20minutemail.com", "2prong.com", "30minutemail.com", "33mail.com",
  "3d-painting.com", "4warding.com", "4warding.net", "4warding.org",
  "airmail.cc", "anonbox.net", "anonymbox.com", "antichef.com", "antichef.net",
  "antispam.de", "armyspy.com", "bccto.me", "beefmilk.com", "binkmail.com",
  "bio-muesli.net", "boun.cr", "bouncr.com", "boximail.com", "briggsmarcus.com",
  "broadbandninja.com", "bsnow.net", "bspamfree.org", "bugmenot.com",
  "bumpymail.com", "burnermail.io", "byom.de", "chacuo.net", "chogmail.com",
  "cool.fr.nf", "correo.blogos.net", "cosmorph.com", "courriel.fr.nf",
  "courrieltemporaire.com", "cubiclink.com", "curryworld.de", "cust.in",
  "dacoolest.com", "dandikmail.com", "dayrep.com", "deadaddress.com",
  "despam.it", "devnullmail.com", "dfgh.net", "digitalsanctuary.com",
  "discard.email", "discardmail.com", "discardmail.de", "dispomail.eu",
  "disposableaddress.com", "disposableinbox.com", "dispose.it",
  "disposeamail.com", "disposemail.com", "dispostable.com", "dodgeit.com",
  "dodgit.com", "dodgit.org", "donemail.ru", "dontreg.com", "dontsendmespam.de",
  "drdrb.com", "drdrb.net", "duck2.club", "dumpandjunk.com", "dumpyemail.com",
  "e-mail.com", "e-mail.org", "e4ward.com", "einmalmail.de", "einrot.com",
  "einrot.de", "eintagsmail.de", "email60.com", "emailgo.de", "emailias.com",
  "emailigo.de", "emailinfive.com", "emailisvalid.com", "emaillime.com",
  "emailmiser.com", "emailondeck.com", "emailproxsy.com", "emails.ne.jp",
  "emailsensei.com", "emailtemporanea.com", "emailtemporanea.net",
  "emailtemporario.com.br", "emailthe.net", "emailtmp.com", "emailwarden.com",
  "emailx.at.hm", "emailxfer.com", "emeil.in", "emeil.ir", "emkei.cf",
  "emkei.ga", "emkei.gq", "emkei.ml", "emkei.tk", "evopo.com", "explodemail.com",
  "fakeinbox.com", "fakeinformation.com", "fakemail.fr", "fakemailz.com",
  "fansworldwide.de", "fantasymail.de", "fastacura.com", "fastchevy.com",
  "fastchrysler.com", "fastkawasaki.com", "fastmazda.com", "fastmitsubishi.com",
  "fastnissan.com", "fastsubaru.com", "fastsuzuki.com", "fasttoyota.com",
  "fastyamaha.com", "filzmail.com", "fizmail.com", "fleckens.hu", "frapmail.com",
  "friendlymail.co.uk", "fux0ringduh.com", "garliclife.com", "gehensiemirnichtaufdensack.de",
  "get1mail.com", "get2mail.fr", "getairmail.com", "getmails.eu", "getnada.com",
  "getonemail.com", "getonemail.net", "ghosttexter.de", "girlsundertheinfluence.com",
  "gishpuppy.com", "gmial.com", "goemailgo.com", "gotmail.com", "gotmail.net",
  "gotmail.org", "gotti.otherinbox.com", "great-host.in", "greensloth.com",
  "grr.la", "gsrv.co.uk", "guerillamail.biz", "guerillamail.com", "guerillamail.de",
  "guerillamail.info", "guerillamail.net", "guerillamail.org", "guerrillamail.biz",
  "guerrillamail.com", "guerrillamail.de", "guerrillamail.info", "guerrillamail.net",
  "guerrillamail.org", "guerrillamailblock.com", "haltospam.com", "harakirimail.com",
  "hat-geld.de", "hatespam.org", "hidemail.de", "hidzz.com", "hmamail.com",
  "hopemail.biz", "ieh-mail.de", "ikbenspamvrij.nl", "imails.info", "incognitomail.com",
  "incognitomail.net", "incognitomail.org", "insorg-mail.info", "instant-mail.de",
  "ipoo.org", "irish2me.com", "iwi.net", "jetable.com", "jetable.fr.nf",
  "jetable.net", "jetable.org", "jnxjn.com", "jourrapide.com", "jsrsolutions.com",
  "kasmail.com", "kaspop.com", "keepmymail.com", "killmail.com", "killmail.net",
  "kir.ch.tc", "klassmaster.com", "klzlk.com", "koszmail.pl", "kurzepost.de",
  "lawlita.com", "letthemeatspam.com", "lhsdv.com", "lifebyfood.com",
  "link2mail.net", "litedrop.com", "loadby.us", "login-email.ga", "lol.ovpn.to",
  "lookugly.com", "lopl.co.cc", "lortemail.dk", "lr78.com", "lroid.com",
  "lukop.dk", "m21.cc", "mail-filter.com", "mail-temporaire.fr", "mail.by",
  "mail.mezimages.net", "mail.zp.ua", "mail1a.de", "mail21.cc", "mail2rss.org",
  "mail333.com", "mail4trash.com", "mailbidon.com", "mailbiz.biz", "mailblocks.com",
  "mailbucket.org", "mailcat.biz", "mailcatch.com", "mailde.de", "mailde.info",
  "maildrop.cc", "maildx.com", "maileater.com", "mailexpire.com", "mailfa.tk",
  "mailforspam.com", "mailfreeonline.com", "mailguard.me", "mailimate.com",
  "mailin8r.com", "mailinater.com", "mailinator.com", "mailinator.net",
  "mailinator.org", "mailinator2.com", "mailincubator.com", "mailismagic.com",
  "mailme.lv", "mailmetrash.com", "mailmoat.com", "mailms.com", "mailnator.com",
  "mailnesia.com", "mailnull.com", "mailorg.org", "mailpick.biz", "mailrock.biz",
  "mailscrap.com", "mailshell.com", "mailsiphon.com", "mailslapping.com",
  "mailslite.com", "mailtemp.info", "mailtome.de", "mailtothis.com", "mailtrash.net",
  "mailtv.net", "mailtv.tv", "mailzilla.com", "mailzilla.org", "makemetheking.com",
  "manybrain.com", "mbx.cc", "mega.zik.dj", "meinspamschutz.de", "meltmail.com",
  "messagebeamer.de", "mierdamail.com", "mintemail.com", "misterpinball.de",
  "moburl.com", "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
  "msa.minsmail.com", "mt2009.com", "mt2014.com", "mycard.net.ua", "mycleaninbox.net",
  "mymail-in.net", "mypacks.net", "mypartyclip.de", "myphantomemail.com",
  "myspaceinc.com", "myspaceinc.net", "myspaceinc.org", "myspacepimpedup.com",
  "myspamless.com", "mytempemail.com", "mytempmail.com", "mytrashmail.com",
  "nabuma.com", "neomailbox.com", "nepwk.com", "nervmich.net", "nervtmich.net",
  "netmails.com", "netmails.net", "neverbox.com", "nice-4u.com", "nincsmail.com",
  "nincsmail.hu", "nnh.com", "no-spam.ws", "noblepioneer.com", "nomail.pw",
  "nomail.xl.cx", "nomail2me.com", "nomorespamemails.com", "nospam.wins.com.br",
  "nospam4.us", "nospamfor.us", "nospammail.net", "notmailinator.com",
  "nowmymail.com", "nurfuerspam.de", "objectmail.com",
  "obobbo.com", "odaymail.com", "onewaymail.com", "onlatedotcom.info",
  "online.ms", "oopi.org", "ordinaryamerican.net", "otherinbox.com",
  "ovpn.to", "owlpic.com", "pancakemail.com", "pcusers.otherinbox.com",
  "pjjkp.com", "plexolan.de", "politikerclub.de", "poofy.org",
  "pookmail.com", "privacy.net", "privatdemail.net", "proxymail.eu",
  "prtnx.com", "punkass.com", "putthisinyourspamdatabase.com", "quickinbox.com",
  "rcpt.at", "reallymymail.com", "recode.me", "recursor.net", "regbypass.com",
  "regbypass.comsafe-mail.net", "rejectmail.com", "reliable-mail.com",
  "rhyta.com", "rmqkr.net", "royal.net", "rppkn.com", "rtrtr.com", "s0ny.net",
  "safe-mail.net", "safersignup.de", "safetymail.info", "safetypost.de",
  "sandelf.de", "saynotospams.com", "schafmail.de", "schrott-email.de",
  "secretemail.de", "secure-mail.biz", "selfdestructingmail.com", "sendspamhere.com",
  "sharklasers.com", "shieldedmail.com", "shiftmail.com", "shitmail.me",
  "shitware.nl", "shmeriously.com", "shortmail.net", "sibmail.com", "sinnlos-mail.de",
  "siteposter.net", "skeefmail.com", "slaskpost.se", "smashmail.de",
  "smellfear.com", "snakemail.com", "sneakemail.com", "sneakmail.de",
  "snkmail.com", "sofimail.com", "sofort-mail.de", "sogetthis.com", "soodonims.com",
  "spam.la", "spam.su", "spam4.me", "spamail.de", "spamarrest.com", "spambob.com",
  "spambob.net", "spambob.org", "spambog.com", "spambog.de", "spambog.ru",
  "spambox.info", "spambox.us", "spamcannon.com", "spamcannon.net", "spamcero.com",
  "spamcon.org", "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net",
  "spamcowboy.org", "spamday.com", "spamex.com", "spamfree24.com", "spamfree24.de",
  "spamfree24.eu", "spamfree24.info", "spamfree24.net", "spamfree24.org",
  "spamgoes.com", "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spamherelots.com", "spamhereplease.com", "spamhole.com", "spamify.com",
  "spaminator.de", "spamkill.info", "spaml.com", "spaml.de", "spammotel.com",
  "spamobox.com", "spamoff.de", "spamsalad.in", "spamslicer.com", "spamspot.com",
  "spamthis.co.uk", "spamthisplease.com", "spamtroll.net", "speed.1s.fr",
  "supergreatmail.com", "supermailer.jp", "superrito.com", "superstachel.de",
  "suremail.info", "talkinator.com", "teewars.org", "teleworm.com", "teleworm.us",
  "temp-mail.com", "temp-mail.de", "temp-mail.io", "temp-mail.org",
  "temp-mail.ru", "tempail.com", "tempalias.com", "tempe-mail.com", "tempemail.biz",
  "tempemail.co.za", "tempemail.com", "tempemail.net", "tempinbox.co.uk",
  "tempinbox.com", "tempmail.co", "tempmail.de", "tempmail.email", "tempmail.eu",
  "tempmail.it", "tempmail.us", "tempmail2.com", "tempmaildemo.com",
  "tempmailer.com", "tempmailer.de", "tempomail.fr", "temporarily.de",
  "temporarioemail.com.br", "temporaryemail.net", "temporaryemail.us",
  "temporaryforwarding.com", "temporaryinbox.com", "temporarymailaddress.com",
  "tempthe.net", "thanksnospam.info", "thankyou2010.com", "thisisnotmyrealemail.com",
  "throam.com", "throwam.com", "throwawayemailaddress.com", "throwawaymail.com",
  "tilien.com", "tittbit.in", "tmail.ws", "tmailinator.com", "toomail.biz",
  "topranklist.de", "tradermail.info", "trash-mail.at", "trash-mail.com",
  "trash-mail.de", "trash2009.com", "trashdevil.com", "trashemail.de",
  "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.me", "trashmail.net",
  "trashmail.org", "trashmail.ws", "trashmailer.com", "trashymail.com",
  "trashymail.net", "trbvm.com", "trialmail.de", "trillianpro.com", "tyldd.com",
  "uggsrock.com", "upliftnow.com", "uplipht.com", "uroid.com", "us.af",
  "venompen.com", "veryrealemail.com", "viditag.com", "viralplays.com",
  "vpn.st", "vsimcard.com", "vubby.com", "wasteland.rfc822.org", "webemail.me",
  "weg-werf-email.de", "wegwerf-emails.de", "wegwerfadresse.de", "wegwerfemail.com",
  "wegwerfemail.de", "wegwerfmail.de", "wegwerfmail.info", "wegwerfmail.net",
  "wegwerfmail.org", "wetrainbayarea.com", "wetrainbayarea.org", "wh4f.org",
  "whyspam.me", "willselfdestruct.com", "winemaven.info", "wronghead.com",
  "wuzup.net", "wuzupmail.net", "www.e4ward.com", "www.mailinator.com",
  "wwwnew.eu", "x.ip6.li", "xagloo.com", "xemaps.com", "xents.com",
  "xmaily.com", "xoxy.net", "yapped.net", "yep.it", "yogamaven.com",
  "yopmail.com", "yopmail.fr", "yopmail.net", "ypmail.webarnak.fr.eu.org",
  "yuurok.com", "z1p.biz", "za.com", "zehnminuten.de", "zehnminutenmail.de",
  "zippymail.info", "zoemail.net", "zomg.info",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.trim().toLowerCase().split("@")[1];
  if (!domain) return false;
  if (DISPOSABLE_DOMAINS.has(domain)) return true;
  // Match subdomains of known disposable providers (e.g. "foo.mailinator.com").
  for (const d of DISPOSABLE_DOMAINS) {
    if (domain.endsWith("." + d)) return true;
  }
  return false;
}

export function getDisposableDomain(email: string): string | null {
  const domain = email.trim().toLowerCase().split("@")[1];
  if (!domain) return null;
  if (DISPOSABLE_DOMAINS.has(domain)) return domain;
  for (const d of DISPOSABLE_DOMAINS) {
    if (domain.endsWith("." + d)) return d;
  }
  return null;
}
