// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-notebooks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_notebooks_default = defineTool({
  name: "list_notebooks",
  title: "List notebooks",
  description: "List the signed-in user's notebooks (excluding trashed).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("notebooks").select("id, name, emoji, parent_id, created_at, updated_at").is("deleted_at", null).order("updated_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notebooks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-notes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_notes_default = defineTool2({
  name: "list_notes",
  title: "List notes",
  description: "List notes for the signed-in user. Optionally filter by notebook_id (pass 'standalone' for top-level notes with no notebook). Returns note metadata without full content.",
  inputSchema: {
    notebook_id: z.string().optional().describe("Notebook ID, or 'standalone' for top-level notes, or omit for all notes."),
    limit: z.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ notebook_id, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser2(ctx).from("notes").select("id, title, emoji, tags, notebook_id, created_at, updated_at").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit);
    if (notebook_id === "standalone") query = query.is("notebook_id", null);
    else if (notebook_id) query = query.eq("notebook_id", notebook_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-note.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_note_default = defineTool3({
  name: "get_note",
  title: "Get note",
  description: "Fetch a single note (including its full markdown content) by id.",
  inputSchema: { id: z2.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("notes").select("id, title, emoji, tags, notebook_id, content, created_at, updated_at").eq("id", id).is("deleted_at", null).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Note not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/search-notes.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_notes_default = defineTool4({
  name: "search_notes",
  title: "Search notes",
  description: "Full-text search across the signed-in user's note titles and content. Returns matching notes with a short snippet.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Search text to match against titles and content."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const like = `%${query.replace(/[%_]/g, (m) => "\\" + m)}%`;
    const { data, error } = await supabaseForUser4(ctx).from("notes").select("id, title, emoji, tags, notebook_id, content, updated_at").is("deleted_at", null).or(`title.ilike.${like},content.ilike.${like}`).order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((n) => {
      const c = n.content ?? "";
      const idx = c.toLowerCase().indexOf(query.toLowerCase());
      const snippet = idx >= 0 ? c.slice(Math.max(0, idx - 60), Math.min(c.length, idx + 140)) : c.slice(0, 160);
      return {
        id: n.id,
        title: n.title,
        emoji: n.emoji,
        tags: n.tags,
        notebook_id: n.notebook_id,
        updated_at: n.updated_at,
        snippet
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(results) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/create-note.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_note_default = defineTool5({
  name: "create_note",
  title: "Create note",
  description: "Create a new note for the signed-in user. Provide notebook_id to nest it inside a notebook, or omit for a standalone top-level note.",
  inputSchema: {
    title: z4.string().trim().min(1).max(200),
    content: z4.string().default(""),
    notebook_id: z4.string().uuid().optional(),
    emoji: z4.string().max(8).optional(),
    tags: z4.array(z4.string()).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, notebook_id, emoji, tags }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser5(ctx).from("notes").insert({
      user_id: ctx.getUserId(),
      title,
      content,
      notebook_id: notebook_id ?? null,
      emoji: emoji ?? null,
      tags: tags ?? null
    }).select("id, title, notebook_id, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created note ${data.id}` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/update-note.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_note_default = defineTool6({
  name: "update_note",
  title: "Update note",
  description: "Update fields on an existing note by id. Only the provided fields are changed. Use `append_content` to add to the end of an existing note without overwriting it.",
  inputSchema: {
    id: z5.string().uuid(),
    title: z5.string().trim().min(1).max(200).optional(),
    content: z5.string().optional().describe("Replaces the full note content."),
    append_content: z5.string().optional().describe("Appends to the end of the existing content (adds a blank line before it)."),
    emoji: z5.string().max(8).optional(),
    tags: z5.array(z5.string()).optional(),
    notebook_id: z5.string().uuid().nullable().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id, title, content, append_content, emoji, tags, notebook_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supa = supabaseForUser6(ctx);
    let nextContent = content;
    if (append_content !== void 0) {
      const { data: existing, error: readErr } = await supa.from("notes").select("content").eq("id", id).maybeSingle();
      if (readErr) return { content: [{ type: "text", text: readErr.message }], isError: true };
      if (!existing)
        return { content: [{ type: "text", text: "Note not found" }], isError: true };
      const base = content ?? existing.content ?? "";
      nextContent = base ? `${base}

${append_content}` : append_content;
    }
    const patch = { updated_at: (/* @__PURE__ */ new Date()).toISOString() };
    if (title !== void 0) patch.title = title;
    if (nextContent !== void 0) patch.content = nextContent;
    if (emoji !== void 0) patch.emoji = emoji;
    if (tags !== void 0) patch.tags = tags;
    if (notebook_id !== void 0) patch.notebook_id = notebook_id;
    const { data, error } = await supa.from("notes").update(patch).eq("id", id).select("id, title, updated_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Updated note ${data.id}` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/create-notebook.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_notebook_default = defineTool7({
  name: "create_notebook",
  title: "Create notebook",
  description: "Create a new notebook for the signed-in user.",
  inputSchema: {
    name: z6.string().trim().min(1).max(120),
    emoji: z6.string().max(8).optional(),
    parent_id: z6.string().uuid().optional().describe("Parent notebook ID for nesting.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, emoji, parent_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser7(ctx).from("notebooks").insert({
      user_id: ctx.getUserId(),
      name,
      emoji: emoji ?? "\u{1F4D3}",
      parent_id: parent_id ?? null
    }).select("id, name, emoji, parent_id, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created notebook ${data.id}` }],
      structuredContent: { notebook: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "unjvbmgnicldmxwmuepc";
var mcp_default = defineMcp({
  name: "notebook-archive-mcp",
  title: "Notebook Archive",
  version: "0.1.0",
  instructions: "Tools for the signed-in user's Notebook Archive workspace. Use `list_notebooks` and `list_notes` to browse, `search_notes` to find content, `get_note` to read a note's full markdown, and `create_note` / `update_note` / `create_notebook` to write. All actions are scoped to the authenticated user via row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_notebooks_default,
    list_notes_default,
    get_note_default,
    search_notes_default,
    create_note_default,
    update_note_default,
    create_notebook_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
